Repository GluuFederation/flex, pull requests merged in 2022-07, with the labels that each got.

#283 fix: flex-linux-setup add admin-ui apache directive
  flex-linux-setup/flex_linux_setup/flex_setup.py
  flex-linux-setup/flex_linux_setup/templates/admin_ui_apache_directive
Labels: bug, comp-flex-linux-setup

#294 fix: flex-linux-setup enable apache module mod_dir (ref: #291)
  flex-linux-setup/flex_linux_setup/flex_setup.py
Labels: comp-flex-linux-setup, kind-bug

#308 chore(main): release casa 5.0.0-1
  casa/CHANGELOG.md
  casa/app/pom.xml
  casa/config/pom.xml
  casa/plugins/bioid/pom.xml
  casa/plugins/cert-authn/pom.xml
  casa/plugins/client-authorizations/pom.xml
  casa/plugins/custom-branding/pom.xml
  casa/plugins/inwebo/pom.xml
  casa/plugins/samples/authentication-script-properties/pom.xml
  casa/plugins/samples/clients-management/pom.xml
  casa/plugins/samples/helloworld/pom.xml
  casa/plugins/samples/sample-cred-plugin/pom.xml
  casa/plugins/strong-authn-settings/pom.xml
  casa/plugins/stytch/pom.xml
  casa/pom.xml
  casa/shared/pom.xml
Labels: autorelease: pending

#313 chore(main): release admin-ui 1.0.0-1
  admin-ui/CHANGELOG.md
  admin-ui/package.json
Labels: autorelease: pending

#309 chore(main): release docker-casa 5.0.0-1
  docker-casa/CHANGELOG.md
Labels: autorelease: pending

#310 chore(main): release docker-admin-ui 1.0.0-1
  docker-admin-ui/CHANGELOG.md
Labels: autorelease: pending

#311 chore(main): release flex-cn-setup 0.1.1
  flex-cn-setup/CHANGELOG.md
Labels: autorelease: pending

#312 chore(main): release flex-linux-setup 0.1.1
  flex-linux-setup/CHANGELOG.md
Labels: autorelease: pending

#319 feat(docker-admin-ui): add support for plugins installation
  docker-admin-ui/.hadolint.yaml
  docker-admin-ui/Dockerfile
  docker-admin-ui/Makefile
  docker-admin-ui/README.md
  docker-admin-ui/scripts/builder.py
  docker-admin-ui/scripts/entrypoint.sh
Labels: area-documentation, comp-docker-admin-ui, kind-feature

#330 fix(docker-casa): upgrade lxml version
  .github/workflows/docker_build_image.yml
  docker-casa/.hadolint.yaml
  docker-casa/Dockerfile
  docker-casa/Makefile
Labels: area-CI, kind-bug, comp-docker-casa

#340 feat: flex-linux-setup non-interactive mode
  flex-linux-setup/flex_linux_setup/flex_setup.py
Labels: comp-flex-linux-setup, kind-feature
