Repository GluuFederation/flex, pull requests merged in 2022-08, with the labels that each got.

#356 chore(images): apply security updates to docker images
  docker-admin-ui/Dockerfile
  docker-admin-ui/Makefile
  docker-casa/Dockerfile
  docker-casa/Makefile
Labels: comp-docker-admin-ui, kind-dependencies, comp-docker-casa

#361 chore: remove jansRequireAuthTime attribute of clients
  docker-admin-ui/templates/clients.ldif
  flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config/templates/upgrade-ldap-101-jans.yaml
  flex-linux-setup/flex_linux_setup/templates/casa_client.ldif
Labels: comp-flex-cn-setup, comp-flex-linux-setup, comp-docker-admin-ui

#365 chore(images): sync templates and schema from upstream
  docker-admin-ui/Dockerfile
  docker-admin-ui/requirements.txt
  docker-casa/Dockerfile
  docker-casa/requirements.txt
Labels: comp-docker-admin-ui, kind-dependencies, comp-docker-casa

#413 chore(main): release casa 5.0.0-2
  casa/CHANGELOG.md
  casa/app/pom.xml
  casa/config/pom.xml
  casa/plugins/bioid/pom.xml
  casa/plugins/cert-authn/pom.xml
  casa/plugins/client-authorizations/pom.xml
  casa/plugins/custom-branding/pom.xml
  casa/plugins/inwebo/pom.xml
  casa/plugins/samples/authentication-script-properties/pom.xml
  casa/plugins/samples/clients-management/pom.xml
  casa/plugins/samples/helloworld/pom.xml
  casa/plugins/samples/sample-cred-plugin/pom.xml
  casa/plugins/strong-authn-settings/pom.xml
  casa/plugins/stytch/pom.xml
  casa/pom.xml
  casa/shared/pom.xml
Labels: autorelease: pending

#409 chore(main): release admin-ui 1.0.1-1
  admin-ui/CHANGELOG.md
  admin-ui/package.json
Labels: autorelease: pending

#408 chore(main): release flex-linux-setup 0.1.2
  flex-linux-setup/CHANGELOG.md
Labels: autorelease: pending

#406 chore(main): release docker-admin-ui 1.0.1-1
  docker-admin-ui/CHANGELOG.md
Labels: autorelease: pending

#405 chore(main): release docker-casa 5.0.0-2
  docker-casa/CHANGELOG.md
Labels: autorelease: pending
