Repository GluuFederation/flex, pull requests merged in 2022-12, with the labels that each got.

#639 chore(main): release casa 5.0.0-SNAPSHOT
  casa/app/pom.xml
  casa/config/pom.xml
  casa/plugins/bioid/pom.xml
  casa/plugins/cert-authn/pom.xml
  casa/plugins/client-authorizations/pom.xml
  casa/plugins/custom-branding/pom.xml
  casa/plugins/inwebo/pom.xml
  casa/plugins/samples/authentication-script-properties/pom.xml
  casa/plugins/samples/clients-management/pom.xml
  casa/plugins/samples/helloworld/pom.xml
  casa/plugins/samples/sample-cred-plugin/pom.xml
  casa/plugins/strong-authn-settings/pom.xml
  casa/plugins/stytch/pom.xml
  casa/pom.xml
  casa/shared/pom.xml
Labels: autorelease: snapshot

#640 chore(main): release docs 5.0.0-4
  docs/CHANGELOG.md
Labels: autorelease: pending

#641 chore(main): release docker-casa 5.0.0-4
  docker-casa/CHANGELOG.md
  docker-casa/version.txt
Labels: autorelease: pending

#645 chore(main): release admin-ui 1.0.5
  admin-ui/CHANGELOG.md
  admin-ui/package.json
Labels: autorelease: pending

#643 chore(main): release flex-cn-setup 1.0.5
  flex-cn-setup/CHANGELOG.md
  flex-cn-setup/pygluu/kubernetes/version.py
Labels: autorelease: pending

#644 chore(main): release flex-linux-setup 1.0.5
  flex-linux-setup/CHANGELOG.md
  flex-linux-setup/flex_linux_setup/version.py
Labels: autorelease: pending

#648 chore(main): release casa 5.0.0-4
  casa/CHANGELOG.md
  casa/app/pom.xml
  casa/config/pom.xml
  casa/plugins/bioid/pom.xml
  casa/plugins/cert-authn/pom.xml
  casa/plugins/client-authorizations/pom.xml
  casa/plugins/custom-branding/pom.xml
  casa/plugins/inwebo/pom.xml
  casa/plugins/samples/authentication-script-properties/pom.xml
  casa/plugins/samples/clients-management/pom.xml
  casa/plugins/samples/helloworld/pom.xml
  casa/plugins/samples/sample-cred-plugin/pom.xml
  casa/plugins/strong-authn-settings/pom.xml
  casa/plugins/stytch/pom.xml
  casa/pom.xml
  casa/shared/pom.xml
Labels: autorelease: pending

#646 chore(main): release 5.0.0-4
  CHANGELOG.md
Labels: autorelease: pending

#656 fix: admin-ui database configuration
  flex-linux-setup/flex_linux_setup/flex_setup.py
  flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
  flex-linux-setup/flex_linux_setup/templates/auiConfiguration.properties
Labels: bug, comp-flex-linux-setup

#670 feat: flex-linux-setup use tarball to install node_modules in admin-ui
  flex-linux-setup/flex_linux_setup/flex_setup.py
Labels: comp-flex-linux-setup, kind-feature

#667 Docs: Filling in installation documentation
  docs/install/helm-install/red-hat-open-shift.md
  docs/install/setup.md
  docs/install/vm-install/disa-stig.md
  docs/install/vm-install/dynamic-download.md
  docs/install/vm-install/rhel.md
  docs/install/vm-install/suse.md
  docs/install/vm-install/ubuntu.md
  docs/install/vm-install/vm-requirements.md
  mkdocs.yml
Labels: area-documentation

#677 [Snyk] Upgrade com.unboundid:unboundid-ldapsdk from 6.0.6 to 6.0.7
  casa/pom.xml
Labels: comp-casa

#689 fix(docker-casa): handle startup errors on postgres, spanner, and couchbase persistence
  docker-casa/Dockerfile
  docker-casa/conf/jans-mysql.properties.tmpl
  docker-casa/conf/jans-pgsql.properties.tmpl
  docker-casa/jetty/casa.xml
  docker-casa/requirements.txt
  docker-casa/scripts/bootstrap.py
  docker-casa/scripts/entrypoint.sh
  docker-casa/scripts/mod_context.py
Labels: kind-bug, comp-docker-casa
