Repository GluuFederation/flex, pull requests merged in 2025-01, with the labels that each got.

#1954 chore(main): release 5.2.0
  CHANGELOG.md
Labels: autorelease: pending

#1955 chore(main): release 5.2.0
  CHANGELOG.md
Labels: autorelease: pending

#1971 feat(flex-linux-setup): application versions via arguments
  flex-linux-setup/flex_linux_setup/flex_setup.py
Labels: comp-flex-linux-setup, kind-feature

#1973 fix(flex-linux-setup): jans-app-build
  flex-linux-setup/flex_linux_setup/flex_setup.py
Labels: comp-flex-linux-setup, kind-bug

#1974 chore(main): release 5.3.0
  CHANGELOG.md
Labels: autorelease: pending

#1962 fix(docs): add documentation for Gluu Solo
  docs/assets/agama-lab/solo-account-details.png
  docs/assets/agama-lab/solo-agama-lab-main-page.png
  docs/assets/agama-lab/solo-billing-details.png
  docs/assets/agama-lab/solo-billing-page.png
  docs/assets/agama-lab/solo-checkout-bill-plan.png
  docs/assets/agama-lab/solo-checkout-confirmation.png
  docs/assets/agama-lab/solo-configuration.png
  docs/assets/agama-lab/solo-creating-new-instance.png
  docs/assets/agama-lab/solo-custom-domain.png
  docs/assets/agama-lab/solo-instance-preview.png
  docs/assets/agama-lab/solo-order-completion.png
  docs/assets/agama-lab/solo-payment-details.png
  docs/assets/agama-lab/solo-payment-success-confirmation.png
  docs/assets/agama-lab/solo-price-confirmation.png
  docs/assets/agama-lab/solo-settings-page.png
  docs/assets/agama-lab/solo-subscription-form-default-domain.png
  docs/assets/agama-lab/solo-subscription-plans.png
  docs/solo/cloud-setup.md
  docs/solo/solo-administration-guide.md
  docs/solo/solo-getting-started.md
  docs/solo/solo-subscription.md
  mkdocs.yml
Labels: area-documentation
